blank_issues_enabled: false
contact_links:
  - name: ImanitySpigot3 Discord
    url: https://discord.gg/GBZKR3n
    about: If you are having issues with settings or have other minor issues, come ask us on our Discord server!
